### ISSUE TITLE
changelog:ent and changelog:dn

### ISSUE THREAD

**Issue by alexmtv** [richm/scripts#22]
Hello Richard!

I have a question about your script dbmon.sh (or for 389 DS db i guess)

The output of the dbmon.sh says:
....
dbcachefree 2374205440 free% 88.446 roevicts 0 hit% 99 pagein 36901 pageout 62843
....
 dbname      count          free  free%    size
changelog:ent        506          4257    0.2  4136.2
changelog:dn       22026       8855857   84.5    74.0
 userroot:ent     139372    1274100674   59.3  6266.6
 userroot:dn      121651     501338704   97.9    87.6
    ipaca:ent         83       9767076   93.1  8658.8
    ipaca:dn          83      10477915   99.9    94.5

I know that the dbcachefree is nsslapd-dbcachesize, userroot:ent is  nsslapd-cachememsize, userroot:dn is nsslapd-dncachememsize.
What is changelog:ent and changelog:dn?

**Comment by richm** [comment]
I don't know why the changelog is showing up in the output.  That means you have a real backend/database defined with that name.  Since dbmon.sh is now part of 389, I have stopped maintaining this script separately.  You should ask on 389-users@lists.fedoraproject.org or in channel \#389 on freenode.
